# Generated by Django 2.1.2 on 2018-10-27 00:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
    ]
