# Generated by Django 2.1.2 on 2018-10-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20181027_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='alcoholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='beverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='pastry',
            field=models.BooleanField(default=False),
        ),
    ]
