# Generated by Django 2.1.2 on 2018-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20181027_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
