# Generated by Django 2.1.2 on 2018-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
