# Generated by Django 2.1.2 on 2018-10-31 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20181027_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.URLValidator()]),
        ),
    ]
